import Head from 'next/head';
import { useContext, useEffect, useState } from 'react';
import ShowProducts from '../../components/ShowProducts';
import { AuthContext } from '../../contexts/AuthContext';
import { IProduct } from '../../datatypes';
import { withAuth } from '../../HOC';
import { likeProduct } from '../../lib/product';

function Likes() {
  const [productLikes, setProductLikes] = useState<IProduct[]>([])
  const {authState: {user}} = useContext(AuthContext)

  useEffect(() => {
    const fetchData = async () => {
      const response = await likeProduct();
      if(response.success) {
        setProductLikes(response.data)
      }
    }

    fetchData()
  }, [user])
  
  return (<>
    <Head>
      <title>NQT Shop</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <ShowProducts products={productLikes} />
  </>)
}

export default withAuth(Likes);