import { Form, Formik, FormikHelpers } from 'formik';
import Head from 'next/head';
import React, { useContext } from 'react';
import { FaHandPointRight } from 'react-icons/fa';
import * as Yup from 'yup';
import InfoShop from '../../components/InfoShop';
import { defaultInfo, Info } from '../../constants/dataDefault';
import { ToastifyContext } from '../../contexts/ToastifyContext';
import { InputField } from "../../custom-field";
import InputTextareaField from '../../custom-field/InputTextareaField';
import { ContactInfo } from '../../datatypes';
import { getInfoShop, sendContactInfo } from '../../lib';
import stylesAuth from '../../styles/Auth.module.css';
import styles from './Contact.module.css';

interface IContactProps {
  infoShop: Info;
}

function Contact({infoShop}: IContactProps) {

  const {showToast} = useContext(ToastifyContext);

  const initialValues: ContactInfo = {
    name: '',
    phone: '',
    email: '',
    description: '',
  }

  const validationSchema = Yup.object().shape({
    name: Yup.string()
      .min(6, 'Tối thiểu 6 ký tự!')
      .required('Vui lòng nhập trường này!')
    ,

    phone: Yup.string()
      .min(10, 'Tối thiểu 10 ký tự!')
      .required('Vui lòng nhập trường này!')
    ,

    email: Yup.string()
      .email("Định dạng địa chỉ email không hợp lệ!")
      .required('Vui lòng nhập trường này!')
    ,

    description: Yup.string()
      .required('Vui lòng nhập trường này!')
    ,
  });

  const handleSubmit = async (values: ContactInfo, { resetForm }: FormikHelpers<ContactInfo>) => { 
    const response = await sendContactInfo(values)

    if(response.success) {
      showToast('Thông tin đã được gửi lên', 'success');
      resetForm();
    }else {
      showToast('Thất bại, lỗi nội bộ', 'error');
    }
  }

  return (<>
    <Head>
      <title>NQT Shop</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className='grid'>
      <div className='row'>
        <div className='col c-12 m-12 l-4'>
          <div className={styles.wrapperInfo}>
            <h2>THÔNG TIN LIÊN HỆ</h2>
            <p>
              NQT Shop xin hân hạnh phục vụ quý khách với những bộ quần áo phục kiện rất nhiều 
              khách hàng tại Việt Nam ưa thích và chọn lựa.
            </p>

            <InfoShop infoShop={infoShop} classes={[styles.font]} />
          </div>
        </div>

        <div className='col c-12 m-12 l-8'>
          <div className={styles.wrapperForm}>
            <div>
              <h2 className={styles.titleInfo}>GỬI THÔNG TIN LÊN SHOP NQT</h2>
              <p className={styles.desInfo}>
                Bạn hãy điền nội dung tin nhắn vào form dưới đây và gửi cho chúng tôi. 
                Chúng tôi sẽ trả lời bạn sau khi nhận được.
              </p>
            </div>
              
            <Formik 
              initialValues={initialValues} 
              validationSchema={validationSchema}
              onSubmit={handleSubmit}
            >
              {() => {
                return (
                  <Form className={styles.form}>
                    <InputField 
                      name='name'
                      placeholder='Vd: Quốc Tuấn'
                      label='Tên đầy đủ'
                      type='text'
                      maxLength={30}
                    />

                    <InputField 
                      name='email'
                      placeholder='Vd: email@dumain.com'
                      label='Email'
                      type='text'
                      maxLength={50}
                    />

                    <InputField 
                      name='phone'
                      placeholder='0987******'
                      label='Điện thoại'
                      type='text'
                      maxLength={13}
                    />

                    <InputTextareaField 
                      name='description'
                      placeholder=''
                      label='Nội dung'

                      classInput={styles.inputArea}
                    />
                    
                    <button type='submit' className={`${stylesAuth.button} ${styles.btn}`}>
                      Gửi Lên Nội Dung
                      <FaHandPointRight />
                    </button>
                  </Form>
                )
              }}
            </Formik>
          </div>
        </div>
      </div>
    </div>
  </>)
} 

export const getStaticProps = async () => {
  const response = await getInfoShop();
  if(!response.success) {
    return {
      props: {
        infoShop: defaultInfo
      } 
    }
  }

  const {infoShop} = response;
  return { 
    props: {
      infoShop: infoShop
    }
  }
}

export default Contact;