import Head from 'next/head';
import { FaClock } from 'react-icons/fa';
import { getNews, getNewsById } from '../../lib';
import styles from './News.module.css';
import { News, Obj } from '../../datatypes';
import { API } from '../../constants';

interface INewsProps {
  news: Obj[]
}

function News({ news }: INewsProps) {
  return (<>
    <Head>
      <title>NQT Shop</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className={styles.wrapper}>
      <h1 className={styles.title}>
        {news[0].value}
      </h1>
      <p className={styles.date}>
        <FaClock />
        {news[0].key}
      </p>

      <li className={styles.list}>
        {
          news.map((newsItem, index) => {
            if (index === 0) return;
            return (
              <ul key={newsItem._id} className={styles.item}>
                {newsItem.value !== 'Not-Found' ? <p className={styles.description}>{newsItem.value}</p> : null}
                {newsItem.key !== 'Not-Found' ? <img className={styles.img} src={`${API}/images/${newsItem.key}`} alt="Ảnh" /> : null}
              </ul>
            )
          })
        }
      </li>
    </div>
  </>)
};

export const getStaticPaths = async () => {
  const response = await getNews();
  const paths = response.data.map((value: News) => ({
    params: {
      id: `${value.title.replace(/\?/g, '').replace(/ /g, '-')}.${value._id}`,
    },
  }));
  console.log("paths:", paths);
  return {
    paths,
    fallback: false, // bất kỳ path nào k return bởi getStaticPath sẽ tự động qua trang 404
  }
};

export const getStaticProps = async ({ params }: any) => {
  const arrayParams = params.id.split(".");
  const response = await getNewsById(arrayParams[arrayParams.length - 1]);

  return {
    props: {
      news: response.data.values,
    },
    revalidate: 1,
  };
}

export default News;