import Head from 'next/head';
import ItemNews from '../../components/ItemNews';
import { NavLink } from '../../custom-link';
import { News } from '../../datatypes';
import { getNews } from '../../lib';
import styles from './News.module.css';

interface IIndexNew {
  news: News[];
}

function IndexNew({news}: IIndexNew) {

  return (<>
    <Head>
      <title>NQT Shop</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
 
    <div className={`row ${styles.wrapperIndex}`}>
      {
        news?.map((value) => (
          <NavLink key={value._id} href={`/news/${value.title.replace(/\?/g, '').replace(/ /g, '-')}.${value._id}`}>
            <div className={`c-12 m-6 l-3`}>
              <ItemNews news={value} />
            </div>
          </NavLink>
        ))
      }
    </div>
  </>)
};

export const getServerSideProps = async () => {
  const response = await getNews();

  if(!response.success){
    // Return sang trang 404
    return {
      notFound: true, // 404 page
    }
  }

  return {
    props: {
      news: response.data,
    }
  };
}

export default IndexNew;